### ISSUE TITLE
TASK: Security

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/take-control-api#16]
## Acceptance Criteria

1. All secret keys, passwords etc. are hidden
2. Debug set to false

## Tasks

- [x] Explicitly set debug to false at code level
- [x] Check everything that needs to be hidden is
- [x] Check security documented in README

**Comment by GeorginaCarlisle** [comment]
Tasks completed.
